server:
  port: 16001

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
   # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # For H2
    # 存储在文件中
    url: jdbc:h2:file:~/.h2/advert-server-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialize: false   # 是否初始化
    # 导入编码
    sql-script-encoding: UTF-8
    continue-on-error: false

    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #  useGlobalDataSourceStat=true
  h2:
    console:
      enabled: true # 是否允许访问控制台
      path: /h2-console # 配置h2控制台访问路径 默认 /h2-console
url:
  upload-server: http://101.201.56.48:8765/api/upload-server/