server:
  port: 16090
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:18761/eureka/
  instance:
    status-page-url: http://${zuul.address}${zuul.api-url}swagger-ui.html
zuul:
  address: ${address:192.168.1.10:18765}
  api-url: ${api-url:/api/alipay-gw/}
logging:
  level:
    root: info
spring:
  thymeleaf:
    cache: false  # 是否开启thymeleaf缓存
    suffix: .html # 后缀
    model: HTML5  #模式
    encoding: UTF8  #编码
    content-type: text/html #内容类型
wetool:
  js-pay-url:
    dev: http://wtpay.viphk.ngrok.org/unify/jsPay
    pro: http://pay:16080/unify/jsPay
    st: http://pay:16080/unify/jsPay