info:
  description: 微兔微服务
  url: https://www.wetool.com

eureka:
  client:
    serviceUrl:
#      defaultZone: http://${LV1_DISCOVERY_1_PORT_8761_TCP_ADDR:localhost}:${LV1_DISCOVERY_1_PORT_8761_TCP_PORT:8761}/eureka/
      defaultZone: http://eureka:8761/eureka/
spring:
  cloud:
    stream: 
       bindings:
         springCloudBusInput:
           destination: testExchange
           group: testQueue
         springCloudBusOutput:
           destination: testExchange
           group: testQueue
  rabbitmq:
#    host: ${LV1_RABBITMQ_1_PORT_5672_TCP_ADDR:localhost}
#    port: ${LV1_RABBITMQ_1_PORT_5672_TCP_PORT:5672}
    host: rabbitmq
    port: 5672
    username: admin
    password: admin