info:
  description: 微兔微服务
  url: https://www.wetool.com

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_PORT_8761_TCP_ADDR}:${DISCOVERY_PORT_8761_TCP_PORT}/eureka/

spring:
  cloud:
    stream: 
       bindings:
         springCloudBusInput:
           destination: testExchange
           group: testQueue
         springCloudBusOutput:
           destination: testExchange
           group: testQueue
  rabbitmq:
    host: ${RABBITMQ_PORT_5672_TCP_ADDR}
    port: ${RABBITMQ_PORT_5672_TCP_PORT}
    username: guest
    password: guest