info:
  description: 微兔微服务
  url: https://www.wetool.com

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_PORT_8761_TCP_ADDR:localhost}:${DISCOVERY_PORT_8761_TCP_PORT:8761}/eureka/

spring:
  cloud:
    stream: 
       bindings:
         springCloudBusInput:
           destination: testExchange
           group: testQueue
         springCloudBusOutput:
           destination: testExchange
           group: testQueue
  rabbitmq:
    host: ${RABBITMQ_PORT_5672_TCP_ADDR:localhost}
    port: ${RABBITMQ_PORT_5672_TCP_PORT:5672}
    username: guest
    password: guest