info:
  description: 微兔微服务
  url: https://www.wetool.com
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:${vcap.services.${PREFIX:}configserver.credentials.uri:http://user:password@localhost:8888}}
      discovery: 
        enabled: true
        serviceId: config-server
    stream: 
       bindings:
         springCloudBusInput:
           destination: testExchange
           group: testQueue
         springCloudBusOutput:
           destination: testExchange
           group: testQueue
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型