info:
  description: 微兔微服务
  url: https://www.wetool.com

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    stream:
       bindings:
         springCloudBusInput:
           destination: testExchange
           group: testQueue
         springCloudBusOutput:
           destination: testExchange
           group: testQueue
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest