server:
  port: 16011

dynamic-ds:
  base:
    # For Mysql
    url: jdbc:mysql://localhost:3306/
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver

spring:
  jpa:
    show-sql: true
    hibernate:
      naming-strategy: com.wetool.jpa.CustomNamingStrategy
  # 配置数据源
  datasource:
    initialize: false   # 是否初始化