server:
  port: 16011

dynamic-ds:
    type: com.alibaba.druid.pool.DruidDataSource
    # For Mysql
    url: jdbc:mysql://localhost:3306/commodity?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    
    
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update