server:
  port: 7000
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:18761/eureka/
      
logging:
  level:
    root: INFO
    com.wetool.push.server.*: DEBUG

netty:  #Netty服务配置
  port: 3333
  read.idel.timeout: 20
  write.idel.timeout: 10
  all.idel.timeout: 0

#线程池设置
tpool:
  corePoolSize: 1
  MaxPoolSize: 1000
  keepAliveSeconds: 300

#对象池设置
#kryopool.maxPoolSize=10000
#dispatcher.sleepTime=100

url:
  auth-server: http://auth:14000   #认证服务
  mac-server: http://mac:16000   #设备服务
  commodity-server: http://commodity:16010   #商品服务


spring:
  cloud:
    stream:
      instanceIndex: 0
      instanceCount: 1
      bindings:
        push_input_channel:
          destination: topic-push
          group: push
          binder: push_binder
      binders:
        push_binder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq
                port: 5672
                username: admin
                password: admin
                virtual-host: /
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
    virtual-host: /

security:
  oauth2:
    client:
      client-id: admin
      client-secret: admin
    resource:
      token-info-uri: http://auth:14000/oauth/check_token

feign:
  oauth2:
    enabled: true
  hystrix:
    enabled: false