server:
  port: 8081

spring:
  cloud:
    stream:
      instanceIndex: 0
      instanceCount: 1
      bindings:
        sms_output_channel:
          destination: topic-sms
          group: sms
          binder: sms_binder
        sms_input_channel:
          destination: topic-sms
          group: sms
          binder: sms_binder
      binders:  
        sms_binder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.1.75
                port: 5672
                username: guest
                password: guest
                virtual-host: /

#业务属性↴
cloopen:  #云通讯平台接入配置
  url: app.cloopen.com  #生产环境（用户应用上线使用）
  port: 8883  #端口
  account:
    sid: aaf98f8945f991db0145f9ed9389005b   #帐号
    token: 57312a8ab3a043d2b28beb7be7fed8b7 #令牌
  appid: aaf98f8945f991db0145fa1cd5da0083 #应用ID
  template: #模板ID
    default: 91752  #短信验证码模板ID
  