server:
  port: 5030
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
      
spring:
  cloud:
    stream:
      instanceIndex: 0
      instanceCount: 1
      bindings:
        sms_output_channel:
          destination: topic-sms
          group: sms
          binder: sms_binder
        sms_input_channel:
          destination: topic-sms
          group: sms
          binder: sms_binder
      binders:  
        sms_binder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq
                port: 5672
                username: guest
                password: guest
                virtual-host: /
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
    virtual-host: /

alidayu: #阿里大于
  url: http://gw.api.taobao.com/router/rest #
  appKey: 23888280 
  appSecret: c14ff71982aac7191e9605b83982db01
  signName: 微兔科技 #阿里大于短信签名
  templateCodeDefault: SMS_69780153 #默认短信模板
  templateCodeRegister: SMS_69870254 #注册短信模板
  templateCodePassword: SMS_69830246 #修改密码短信模板