server:
  port: 15031

spring:
  cloud:
    stream:
      instanceIndex: 0
      instanceCount: 2
      default-binder: sms_binder2
      bindings:
        sms_output_channel:
          destination: topic-sms
          group: sms
          binder: sms_binder
        sms_input_channel:
          destination: topic-sms
          group: sms
          binder: sms_binder2
      binders:
        sms_binder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
        sms_binder2:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.1.52
                port: 5672
                username: guest
                password: guest
                virtual-host: /
#业务属性↴
cloopen:  #云通讯平台接入配置
  url: sandboxapp.cloopen.com #沙盒环境（用于应用开发调试）
  port: 8883
  account:
    sid: aaf98f8945f991db0145f9ed9389005b   #帐号
    token: 57312a8ab3a043d2b28beb7be7fed8b7 #令牌
  appid: aaf98f8945f991db0145fa1cd5da0083 #应用ID
  template: #模板ID
    default: 91752  #短信验证码模板ID