server:
  port: 12898

spring:
  cloud:
    stream:
      instanceIndex: 0
      instanceCount: 1
      bindings:
        order_offline_output_channel: #线下订单生产通道
          destination: order-offline 
          group: orderOffline
          binder: test_binder
        payment_offline_output_channel: #线下支付生产通道
          destination: payment-offline
          group: payment
          binder: test_binder
        payment_online_output_channel: #线上支付生产通道
          destination: payment-online
          group: payment
          binder: test_binder          

      binders:  
        test_binder: 
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
#  rabbitmq:
#    host: 192.168.1.10
#    port: 5672
#    username: admin
#    password: admin
#    virtual-host: /
    
  velocity: 
    charset: UTF-8 
    resourceLoaderPath: classpath:/templates/ 
    suffix: .html 
    properties: 
      input: 
        encoding: UTF-8 
      output: 
        encoding: UTF-8 
