server:
  port: 12898

spring:
  cloud:
    stream:
      instanceIndex: 0
      instanceCount: 1
      bindings:
        order_output_channel:
          destination: order-offline 
          group: orderOffline
          binder: test_binder
        invoicing_input_channel: 
          destination: topic-invoicing
          group: invoicing
          binder: test_binder

      binders:  
        test_binder: 
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
                
  velocity: 
    charset: UTF-8 
    resourceLoaderPath: classpath:/templates/ 
    suffix: .html 
    properties: 
      input: 
        encoding: UTF-8 
      output: 
        encoding: UTF-8 

