server:
  port: 12898

spring:
  cloud:
    stream:
      instanceIndex: 0
      instanceCount: 1
      bindings:
        order_output_channel:
          destination: order-offline 
          group: orderOffline
          binder: test_binder
        payment_output_channel: 
          destination: payment-status
          group: payment
          binder: test_binder

      binders:  
        test_binder: 
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
