server:
  port: 8082
  
spring:  
  cloud:  
    stream:
      instanceIndex: 0
      instanceCount: 1
      bindings:  
        sms_output_channel:
          destination: topic-sms
          group: sms
          binder: sms_binder
      binders:
        sms_binder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.1.75
                port: 5672
                username: guest
                password: guest
                virtual-host: /
  data:
    mongodb:
      uri: ${vcap.services.${PREFIX:}mongodb.credentials.uri:mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/areas}
