server:
  port: 8082
  
spring:  
  cloud:  
    stream:
      instanceIndex: 0
      instanceCount: 1
      bindings:  
        sms_output_channel:
          destination: topic-sms
          group: sms
          binder: sms_binder
      binders:
        sms_binder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.1.110
                port: 5672
                username: guest
                password: guest
                virtual-host: /
  data:
    mongodb:
      uri: mongodb://localhost:27017/areas
     # uri: mongodb://name:pass@localhost:27017/areas