server:
  port: 15021

# REDIS (RedisProperties)
spring:
  redis:
    database: 0 # database name  
    host: localhost # server host  
    password:   # server password  
    port: 6379    # connection port  
    pool: # pool settings ...
      max-idle: 150
      min-idle: 0
      max-active: 1000
      max-wait: -1
# sentinel:
#   master:  # name of Redis server
#   nodes:    # comma-separated list of host:port pairs

#业务属性↴
aliyun: #aliyun OSS info
  oss: 
    access_id: LTAIrEv8URC1EymP
    access_key: OZ8seK2tYRSo3AsvDGak30xgIsZQrq
    endpoint: http://oss-cn-beijing.aliyuncs.com/
    bucket_name: wetool
    file_path: http://wetool.oss-cn-beijing.aliyuncs.com/
module: # 模块类型
    types:
      test: ms.test.dev/  #OSS路径
      advert: ms.advert.dev/
      commodity: ms.commodity.dev/