server:
  port: 9411
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:18761/eureka/
logging:
  level:
    root: INFO
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none 
  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://wetool01.mysql.rds.aliyuncs.com:3306/zipkin?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: '{cipher}AIAuv5ZnJF3kvhyijpipsb8GcS4jPm3LvzEGcY1+2MKIsbAbPXkVrgbviYcqXR3S9CNtCj7mglCYDPXAc2vyPSguLdaWQPCxI5P/s07UNegx6ROk7myNCfp9Uv+758Uk+AYENLY8SHQ41ufoI+cTBysGw0tHGu2OARypFrDZeCMVOyip5aAofahfrQ4sJNOBhLlIfSF5Ptec1EAow8h4BV1o'
    password: '{cipher}AICXLXOUzPDqJg9Mbh4qJ5bDbPhkBocF7ZilNxfGccZM8p66m+yFOX+7xyLgT1J/A1jtdk6HupJy0ntUm7JThh2ruXZENwykqN5VPRzbHGhpI09qqM7v0Gs2D0c0+aNW1HAwrkYmE1IbqxNawTpVuRwOqh6m1LbW+I+rbOMC03CpwhxeKlNkRS94t2vYVE4yKplTl7HxtAiYSbqxSHBQJbGi'
    driverClassName: com.mysql.jdbc.Driver
    schema: classpath:sql/schema.sql  # 结构文件
    initialize: false
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #  useGlobalDataSourceStat=true

zipkin:
  storage:
    type: mysql